### ISSUE TITLE
Compilation results in "Invalid static method invocation syntax: "[MSBuild]::IsRunningFromVisualStudio()"

### ISSUE THREAD

**Issue by zanetdev** [Dresel/Automaty#6]
This is due to a change in MSBuild.

Please see below issue for solution and update all msbuild references to use new package

https://github.com/Microsoft/msbuild/issues/2775

**Comment by Dresel** [comment]
Thanks for reporting, will address that asap.

**Comment by Dresel** [comment]
I have updated MSBuild references for `Automaty.Core` and `Automaty.MSBuild` and also uploaded a new NuGet package version for both and `Automaty.DotNetCli`.

Please update your Automaty NuGet package references and let me know if it works for you when you have time to test it.
