### ISSUE TITLE
Tests / Usage with MSBuild 15.6.4+ installed throws MSB0001: Internal MSBuild Error: Missing resource '' error

### ISSUE THREAD

**Issue by zanetdev** [Dresel/Automaty#7]
Trying to run tests from the Automaty repository or actually using Automaty in a project with the --project switch causes the above error. 

Research points to there being a mismatch with the version of msbuild being used vs the version referenced in the project. Unfortunatley I havnt had the resources to solve this issue, but am posting here so if anyone else experiences this issue they at least have an idea that the environment with VS2017 15.6+ is a contributing factor. 

Some relevant pages: 
https://developercommunity.visualstudio.com/content/problem/209174/vs2017-1560-msb0001-error-on-loading-net-core-proj.html

https://www.bountysource.com/issues/55876003-msbuild-errors-when-generating-metadata-for-sdk-based-net461-project-and-vs-2017-15-6

https://developercommunity.visualstudio.com/content/problem/209642/msb0001-internal-msbuild-error-missing-resource.html

**Comment by Dresel** [comment]
Thanks for reporting. Updating Microsoft.Build related packages seems to fix this issue. Going to upload an updated NuGet version tomorrow.

**Comment by Dresel** [comment]
I have updated MSBuild references for Automaty.Core and Automaty.MSBuild and also uploaded a new NuGet package version for both and Automaty.DotNetCli.

Please update your Automaty NuGet package references and let me know if it works for you when you have time to test it.

**Comment by zanetdev** [comment]
Many thanks Christopher for ridiculously quick response.

I can confirm problem resolved on my side
